# Generated by Django 3.1.3 on 2020-12-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_member_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default=24, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='is_administration',
            field=models.BooleanField(default='false'),
        ),
    ]
